-- Script made by JayJax aka Black Book --

-- Radios base
if Config.DistableRadio then
	Citizen.CreateThread(function()
		while true do
			Citizen.Wait(0)
			RadioStations()
			HideHudComponentThisFrame(16)
		end
	end)
end

-- Functions do not touch!
-- Disable Radio
function RadioStations()
	local list = {
		"RADIO_01_CLASS_ROCK",
		"RADIO_02_POP",
		"RADIO_03_HIPHOP_NEW",
		"RADIO_04_PUNK",
		"RADIO_05_TALK_01",
		"RADIO_06_COUNTRY",
		"RADIO_07_DANCE_01",
		"RADIO_08_MEXICAN",
		"RADIO_09_HIPHOP_OLD",
		"RADIO_11_TALK_02",
		"RADIO_12_REGGAE",
		"RADIO_13_JAZZ",
		"RADIO_14_DANCE_02",
		"RADIO_15_MOTOWN",
		"RADIO_16_SILVERLAKE",
		"RADIO_17_FUNK",
		"RADIO_20_THELAB",
		"RADIO_16_SILVERLAKE",
		"RADIO_17_FUNK",
		"RADIO_18_90S_ROCK",
		"RADIO_18_90S_ROCK",
		"RADIO_21_DLC_XM17",
		"RADIO_22_DLC_BATTLE_MIX1_RADIO",
		"RADIO_19_USER",
		"HIDDEN_RADIO_AMBIENT_TV",
		"HIDDEN_RADIO_AMBIENT_TV_BRIGHT",
		"HIDDEN_RADIO_01_CLASS_ROCK",
		"HIDDEN_RADIO_ADVERTS",
		"HIDDEN_RADIO_02_POP",
		"HIDDEN_RADIO_03_HIPHOP_NEW",
		"HIDDEN_RADIO_04_PUNK",
		"HIDDEN_RADIO_06_COUNTRY",
		"HIDDEN_RADIO_07_DANCE_01",
		"HIDDEN_RADIO_09_HIPHOP_OLD",
		"HIDDEN_RADIO_12_REGGAE",
		"HIDDEN_RADIO_15_MOTOWN",
		"HIDDEN_RADIO_16_SILVERLAKE",
		"RADIO_22_DLC_BATTLE_MIX1_CLUB",
		"HIDDEN_RADIO_STRIP_CLUB",
		"DLC_BATTLE_MIX1_CLUB_PRIV",
		"HIDDEN_RADIO_BIKER_CLASSIC_ROCK",
		"DLC_BATTLE_MIX2_CLUB_PRIV",
		"HIDDEN_RADIO_BIKER_MODERN_ROCK",
		"RADIO_23_DLC_BATTLE_MIX2_CLUB",
		"RADIO_25_DLC_BATTLE_MIX4_CLUB",
		"DLC_BATTLE_MIX3_CLUB_PRIV",
		"RADIO_26_DLC_BATTLE_CLUB_WARMUP",
		"HIDDEN_RADIO_BIKER_PUNK",
		"RADIO_24_DLC_BATTLE_MIX3_CLUB",
		"DLC_BATTLE_MIX4_CLUB_PRIV",
		"HIDDEN_RADIO_BIKER_HIP_HOP"
	}
	
	for a = 1, #list do
		SetRadioStationDisabled(GetHashKey(list[i]), true)
		LockRadioStation(GetHashKey(list[i]), true)
	end
end
